version: '3'

services:
  tmm:
    image: dzhuang/tinymediamanager:latest
    ports:
      - 5800:5800
      - 5900:5900
    volumes:
      - ./config:/config
      - ./media:/media
    environment:
      GROUP_ID: 1000
      USER_ID: 0
      TZ: Asia/Hong_Kong
